import { Router } from 'express'
import { getCard } from '../../domain/accounts.js'
import { audit } from '../../domain/audit.js'
import { confirmIntent, createIntent, setPin } from '../../domain/pos.js'
import type { OrderRequestItem, PayMethod } from '../../domain/orders.js'
import { renderReceipt } from '../../domain/receipt.js'
import { param, pushBalanceForCard, type StaffDeps } from '../deps.js'
import { requireRole } from '../staffAuth.js'

/**
 * Point of sale: staff take an order face-to-face and the customer taps their
 * card on the same Android tablet (Web NFC).
 *
 * Two steps on purpose. `intent` prices the cart and decides server-side whether
 * this payment is one of the 1-in-8 that gets PIN-checked; `confirm` charges it.
 * If the client made that decision it would simply never ask for a PIN.
 *
 * Ordinary staff may take payments — they run the bar. Only admins set PINs.
 */
export function posRouter(deps: StaffDeps): Router {
  const router = Router()

  router.post('/pos/intent', (req, res) => {
    // Note what is NOT read here: the PIN decision. It comes from deps, never
    // from the body — see StaffDeps.posPinDecision.
    const { cardUid, items, pay, customAmountDeni, label, direction } = req.body ?? {}

    if (typeof cardUid !== 'string' || cardUid.trim() === '') {
      res.status(400).json({ ok: false, code: 'unknown_card', error: 'cardUid is required' })
      return
    }

    const isCustom = customAmountDeni !== undefined

    if (isCustom) {
      if (!Number.isInteger(customAmountDeni) || customAmountDeni <= 0 || customAmountDeni > 5_000_000) {
        res.status(400).json({ ok: false, error: 'customAmountDeni must be a positive integer (max 5000000)' })
        return
      }
      if (direction !== undefined && direction !== 'debit' && direction !== 'credit') {
        res.status(400).json({ ok: false, error: 'direction must be debit or credit' })
        return
      }
    } else {
      if (!Array.isArray(items)) {
        res.status(400).json({ ok: false, code: 'empty', error: 'items must be an array' })
        return
      }
    }

    const result = createIntent(deps.db, {
      cardUid,
      ...(isCustom
        ? {
            customAmountDeni,
            label: typeof label === 'string' ? label : undefined,
            direction: direction as 'debit' | 'credit' | undefined
          }
        : {
            items: items as OrderRequestItem[],
            pay: pay === 'points' ? 'points' : ('cash' as PayMethod)
          }),
      staff: req.staff!.username,
      ...(deps.posPinDecision ? { forcePin: deps.posPinDecision() } : {})
    })

    if (!result.ok) {
      res.status(400).json(result)
      return
    }
    res.json(result)
  })

  router.post('/pos/confirm', (req, res) => {
    const { intentId, pin } = req.body ?? {}
    if (typeof intentId !== 'string' || intentId.trim() === '') {
      res.status(400).json({ ok: false, code: 'unknown_intent', error: 'intentId is required' })
      return
    }

    const result = confirmIntent(deps.db, {
      intentId,
      ...(typeof pin === 'string' ? { pin } : {})
    })

    if (!result.ok) {
      res.status(400).json(result)
      return
    }

    audit(deps.db, {
      actor: req.staff!.username,
      action: result.direction === 'credit' ? 'pos.credit' : 'pos.charge',
      entityType: result.orderId ? 'order' : 'intent',
      entityId: result.orderId ?? intentId,
      details: { cardId: result.cardId, balanceDeni: result.balanceDeni }
    })

    // Keep a terminal that's mid-session from showing a stale balance, and put
    // the drink on the bar's live feed.
    pushBalanceForCard(deps, result.cardId)
    if (result.orderId) {
      deps.events.emit('order.created', { orderId: result.orderId })
    }

    res.json(result)
  })

  /**
   * Fiscal receipt image for the guest's printer, generated by the external
   * Receipt Render API. Proxied so its x-api-key never reaches the browser.
   * Any signed-in staff member may print — same gate as the payment routes,
   * and not audited: printing moves nothing, unlike confirm.
   */
  router.post('/pos/receipt', (req, res) => {
    const { items, paymentMethod } = req.body ?? {}
    if (!Array.isArray(items) || items.length === 0) {
      res.status(400).json({ error: 'items must be a non-empty array' })
      return
    }

    void renderReceipt(deps.config, {
      items,
      ...(typeof paymentMethod === 'string' ? { paymentMethod } : {})
    }).then((result) => {
      if (!result.ok) {
        res.status(result.status).json({ error: result.error ?? 'receipt rendering failed', code: result.code })
        return
      }
      res.set('Content-Type', result.contentType)
      res.set('Cache-Control', 'no-store')
      res.send(result.png)
    })
  })

  router.post('/cards/:id/pin', requireRole('admin'), (req, res) => {
    const cardId = param(req, 'id')
    if (!getCard(deps.db, cardId)) {
      res.status(404).json({ error: 'no such card' })
      return
    }

    const { pin } = req.body ?? {}
    if (typeof pin !== 'string' || !/^[0-9]{4}$/.test(pin)) {
      res.status(400).json({ error: 'pin must be exactly 4 digits' })
      return
    }

    setPin(deps.db, cardId, pin)
    // Deliberately records only that a PIN was set — never the PIN itself.
    audit(deps.db, {
      actor: req.staff!.username,
      action: 'card.set_pin',
      entityType: 'card',
      entityId: cardId
    })
    res.json({ ok: true })
  })

  return router
}
